Repository florimondmanca/polyphona, pull requests merged in 2019-02, with the labels that each got.

#21 Midi File export
  .gitignore
  package-lock.json
  package.json
  src/main/index.js
  src/renderer/components/SongEditor/SongEditor.vue
  src/renderer/store/Music.js
  src/renderer/store/modules/MusicStore.js
  test_popup
Labels: Ongoing

#40 Refactor adapters, and other related improvements
  .eslintrc.js
  src/renderer/components/SongEditor/CanvasLine.vue
  src/renderer/components/SongEditor/NoteBox.vue
  src/renderer/components/SongEditor/NoteCanvas.vue
  src/renderer/components/SongEditor/adapters.js
  src/renderer/components/SongEditor/errors.js
  src/renderer/components/SongEditor/utils.js
  src/renderer/store/Music.js
  src/renderer/store/modules/MusicStore.js
  src/renderer/store/music.js
Labels: refactor

#39 Add comments, remove unusued variables and map actions in Home.vue
  src/renderer/components/Home.vue
Labels: refactor

#44 Extract song tools into a SongToolBar component
  src/renderer/App.vue
  src/renderer/components/SongEditor/SongEditor.vue
  src/renderer/components/SongEditor/SongToolBar.vue
  src/renderer/styles/_bootstrap_override.scss
Labels: refactor

#43 Simplify implementation of Note.disturbs()
  src/renderer/store/music.js
Labels: refactor

#45 Refactor canvas layers
  src/renderer/components/SongEditor/CanvasLayers.vue
  src/renderer/components/SongEditor/NoteCanvas.vue
Labels: refactor

#38 Use the original midiconvert library by Tone.js
  README.md
  package-lock.json
  package.json
  src/renderer/store/modules/music.js
Labels: refactor

#46 Refactor canvas components
  src/renderer/components/SongEditor/NoteCanvas.vue
  src/renderer/components/SongEditor/NoteGrid.vue
  src/renderer/components/SongEditor/PitchHeader.vue
  src/renderer/components/SongEditor/ProgressBar.vue
Labels: refactor

#47 Refactor music models
  src/renderer/components/SongEditor/CanvasLayers.vue
  src/renderer/components/SongEditor/CanvasLine.vue
  src/renderer/components/SongEditor/NoteBox.vue
  src/renderer/components/SongEditor/NoteCanvas.vue
  src/renderer/models/.gitkeep
  src/renderer/models/adapters.js
  src/renderer/models/errors.js
  src/renderer/models/index.js
  src/renderer/models/note.js
  src/renderer/models/scales.js
  src/renderer/models/track.js
  src/renderer/models/utils.js
  src/renderer/store/modules/music.js
  src/renderer/store/music.js
Labels: refactor

#37 Configure app for packaging
  build/icons/256x256.png
  build/icons/icon.icns
  build/icons/icon.ico
  package-lock.json
  package.json
  src/index.ejs
Labels: enhancement

#49 Create and use Box class
  src/renderer/components/SongEditor/CanvasLine.vue
  src/renderer/components/SongEditor/NoteBox.vue
  src/renderer/components/SongEditor/NoteCanvas.vue
  src/renderer/components/SongEditor/NoteGrid.vue
  src/renderer/components/SongEditor/ProgressBar.vue
  src/renderer/models/adapters.js
  src/renderer/models/box.js
  src/renderer/models/index.js
Labels: refactor

#22 Cleanup server code
  README.md
  api/__init__.py
  api/db.py
  api/error_handlers.py
  api/factory.py
  api/resources/__init__.py
  api/resources/decorators.py
  api/resources/parsers.py
  api/resources/songs.py
  api/resources/tokens.py
  api/resources/users.py
  api/tests/__init__.py
  api/tests/conftest.py
  api/tests/test_songs/__init__.py
  api/tests/test_songs/conftest.py
  api/tests/test_songs/test_songs_create.py
  api/tests/test_songs/test_songs_delete.py
  api/tests/test_songs/test_songs_list.py
  api/tests/test_songs/test_songs_retrieve.py
  api/tests/test_songs/test_songs_update.py
  api/tests/test_tokens.py
  api/tests/test_users.py
  conftest.py
  pytest.ini
  server/database.py
  server/server.py
  server/server_test.py
Labels: refactor, wild

#50 Create and use User class
  src/renderer/models/index.js
  src/renderer/models/user.js
  src/renderer/store/modules/auth.js
Labels: refactor
